### ISSUE TITLE
Use Deno compile to create single executable 

### ISSUE THREAD

**Issue by gevera** [dbushell/sveltekit-adapter-deno#14]
Great adapter. Thanks for sharing

I wonder.if it's possible to create a single executable file with this Deno adapter.

https://docs.deno.com/runtime/reference/cli/compiler/

My end goal is to set a certain parameter in the adapter, say executable:true

And when running npm run build or deno run build a single file will be generated in build folder

**Comment by dbushell** [comment]
Apparently it is possible someone is doing it https://github.com/dbushell/sveltekit-adapter-deno/pull/10 and an [adapter option](https://github.com/dbushell/sveltekit-adapter-deno?tab=readme-ov-file#adapter-options) was added for `usage: 'deno-compile'` 

I think you just run `deno compile` on the build directory or entry point.

It would be outside the scope of the adapter to build the executable itself.

**Comment by tiloio** [comment]
Yeah @gevera I have done this (see https://github.com/tiloio/sveltekit-deno/blob/40821a0cdd2624ba441784c4fc84a1db0ae9918d/package.json#L7).
But all prerendered files etc. in the static directory have to be copied (`cp -r build/static dist/static`).

To embed these files deno has to support this in the future, see: https://github.com/denoland/deno/issues/20885.
Or we do something with base64 or so in the build step....
