### ISSUE TITLE
Build a plugin system for e.g. ssl and compile

### ISSUE THREAD

**Issue by tiloio** [dbushell/sveltekit-adapter-deno#15]
I want to build a plugin system for this adapter, so that you can opt-in to adapter features like ssl (see https://github.com/tiloio/sveltekit-adapter-deno/blob/20d309f82639bb279f9cc16df5927d007ad4d836/ssl/ssl-plugin.ts#L9).

One problem I encounter is that we can have two plugin steps

1. at buildtime
2. at runtime

I would like to implement the plugin system with an interface that can be imported in an plugin array:
```ts
// some plugin file
export function SslPlugin(): AdapterPlugin {
  return {
    name: "deno-ssl-plugin",
    async init(data) {
      const sslCertificate = await getOrCreateCerficate();

      return {
        newServeOptions: {
          ...data.serveOptions,
          key: sslCertificate.key,
          cert: sslCertificate.cert,
        },
      };
    },
  };
}
```

```ts
// svelte.config.js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      plugins: [
        SslPlugin(),
      ]
    }),
  },
};
```

Plugins for buildtime should be very simple.
But how do I do plugins for the runtime?
How do we compile the plugin code from the function call `SslPlugin()` into the build output?

Maybe someone has an Idea.
I built a not working prototype with this branch: https://github.com/tiloio/sveltekit-adapter-deno/tree/plugin

**Comment by dbushell** [comment]
This sounds cool! 

To be honest though I only have time to maintain small fixes & improvements in this repo. I don't host any SvelteKit projects right now so my interest has faded.

Discussion here is welcome but a plugin system would have to be a fork for now.

I've always proxied SvelteKit (or any Deno server) so it runs insecure locally and then [Caddy](https://caddyserver.com) handle TLS certs and is exposed publicly.
