### ISSUE TITLE
Publish to Svelte Society

### ISSUE THREAD

**Issue by Malix-Labs** [dbushell/sveltekit-adapter-deno#16]
https://www.sveltesociety.dev/help/submitting?type=package

```json
{
	"title": "sveltekit-adapter-deno",
	"repository": "https://github.com/dbushell/sveltekit-adapter-deno",
	"description": "🦕 SvelteKit Adapter for Deno and Deno Deploy",
	"npm": "sveltekit-adapter-deno",
	"categories": [
		"sveltekit-adapters"
	]
}
```

**Comment by dbushell** [comment]
Is this a suggestion or have you submitted?

Let's move discussion to this issue which is similar: https://github.com/dbushell/sveltekit-adapter-deno/issues/5

I've never really had any plans to maintain this adapter so I've been hesitant in advertising it anywhere.

**Comment by Malix-Labs** [comment]
> Is this a suggestion or have you submitted?

I would never submit without your approval, of course

> Let's move discussion to this issue which is similar

Okay !

**Comment by Malix-Labs** [comment]
Duplicate of #5
