### ISSUE TITLE
Unable to change port used by the built server

### ISSUE THREAD

**Issue by HighPriest** [dbushell/sveltekit-adapter-deno#19]
I seem to be unable to change the server port from the default 8000.  

I've tried:
- `PORT=69420 deno run -A /build/mod.ts`
- Adding server: { port: 69420 } to vite.config.ts

How do I do it correctly?

**Comment by dbushell** [comment]
There is an open PR to change the port https://github.com/dbushell/sveltekit-adapter-deno/pull/11
I will merge that today and release a new version

**Comment by dbushell** [comment]
PR was merged `PORT` is available in v0.15

https://github.com/dbushell/sveltekit-adapter-deno#change-the-port-or-hostname

**Comment by HighPriest** [comment]
Thank you @dbushell for rapid response.  
Changing ports works perfectly now, but setting `HOST=69.4.20.1` doesn't alter the host :(  
The server always binds to 0.0.0.0
