### ISSUE TITLE
Publish to JSR instead of NPM

### ISSUE THREAD

**Issue by Malix-Labs** [dbushell/sveltekit-adapter-deno#21]
https://jsr.io/new

**Comment by dbushell** [comment]
Thanks for the suggestion but I'm hesitant to publish to JSR for the same reasons I haven't published to [sveltesociety.dev](https://github.com/dbushell/sveltekit-adapter-deno/issues/5)

1. The adapter only started as a working example for Deno Deploy
2. I've never had any real plans or interest in actively maintaining it
3. It should be obsolete soon with Deno's Node compatibility

Also I have other opinions on JSR but I won't rant here lol

**Comment by Malix-Labs** [comment]
Understandable !

> It should be obsolete soon with Deno's Node compatibility

It already landed and works out of the box in my testings

However I don't think it makes this project obsolete because of https://github.com/dbushell/sveltekit-adapter-deno/issues/5#issuecomment-2436280221

I know a thin mapping API layer is not much but it's still something
