### ISSUE TITLE
Toolchain to Deno 2

### ISSUE THREAD

**Issue by Malix-Labs** [dbushell/sveltekit-adapter-deno#22]
- [ ] Convert `package.json` into `deno.json`
- [ ] Same for `demo/`
- [ ] Update documentation (#20)

**Comment by dbushell** [comment]
Thanks I've left a comment on the PR https://github.com/dbushell/sveltekit-adapter-deno/pull/20#issuecomment-2437062073

I think there is some confusion here regarding Node / Deno.

SvelteKit and its adapters are basically Node projects. Only the built output from this adapter is built for Deno.  Changing package.json to deno.json wouldn't make sense.

At some point SvelteKit and Deno will be fully compatibility with each other, at that time this adapter becomes obsolete.

**Comment by Malix-Labs** [comment]
@dbushell indeed but the toolchain of this repository can be converted to deno, right ?

It has more interest in dev than in prod but it kinda makes sense for a deno project

**Comment by dbushell** [comment]
The toolchain is Node. Only the adapter build output targets Deno to serve the website.

If you mean using Deno for the entire toolchain, for Vite development etc, I don't know if Deno if fully compatible with SvelteKit yet. If it is there is no need for this adapter, using the Node adapter would be perfectly fine.

**Comment by Malix-Labs** [comment]
> If you mean using Deno for the entire toolchain

Yep

> I don't know if Deno if fully compatible with SvelteKit yet

Yes, but not out of the box (see https://github.com/sveltejs/cli/issues/214)
The node adapter is fully compatible

However I don't think it makes this project obsolete because of #5 (comment)

I know a thin mapping API layer is not much but it's still something

**Comment by dbushell** [comment]
I'd recommend starting a fork if you're looking for a full Deno toolchain. Personally I think it'd be a wasted effort I don't see there being anything to gain. You can't escape Node APIs in the SvelteKit dev/build process.

I'll probably archive this repo very soon.
