### ISSUE TITLE
Error: Dynamic require of X is not supported

### ISSUE THREAD

**Issue by drewbitt** [dbushell/sveltekit-adapter-deno#3]
### Error
```bash
error: Uncaught Error: Dynamic require of "fs" is not supported
  throw Error('Dynamic require of "' + x2 + '" is not supported');
```

This is an esbuild error. 

### Cause 

```
// node_modules/.pnpm/better-sqlite3@8.5.0/node_modules/better-sqlite3/lib/database.js
var require_database = __commonJS({
  "node_modules/.pnpm/better-sqlite3@8.5.0/node_modules/better-sqlite3/lib/database.js"(exports, module) {
    "use strict";
    var fs = __require("fs");
    var path = __require("path");
```

The error occurs because esbuild replaces require calls with a __require shim when emitting ESM, since `require` is not available in ESM. This causes issues when targeting Node.js, since Node.js built-in modules like `fs` are marked as external and therefore requiring them fails at runtime.

### Fix

There's a large discussion on this in esbuild as well as a rejected PR. The popular fix is to add a `banner` to pollyfill require. You should probably allow this to be set by the user rather than fill it in with every possible built-in.
https://github.com/evanw/esbuild/pull/2067

**Comment by dbushell** [comment]
Thanks I'll take a look when I'm free. Sounds like allowing customisable esbuild config will be enough.

**Comment by dbushell** [comment]
I've added an optional `buildOptions` to the adapter config.

This allows you to override any [esbuild Build option](https://esbuild.github.io/api/#build).

To add a `banner` for example:

```javascript
import {vitePreprocess} from '@sveltejs/kit/vite';
import adapter from 'sveltekit-adapter-deno';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      buildOptions: {
        banner: {
          js: `/* Build time: ${new Date().toISOString()} */`
        }
      }
    })
  }
};

export default config;
```

I added a console warning if any of the adapter defaults like `entryPoints` are changed.

**Comment by drewbitt** [comment]
This works for adjusting banner! Thanks!
